name: Extract Features and Push Results

on: 
  push:  
    paths:
      - '**/*.gz'
  workflow_dispatch:

jobs: 
  extract_push:
    runs-on: ubuntu-latest

    steps: 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
    
      - name: Checkout Instance Repo
        uses: actions/checkout@v4

      - name: Install Feature Extractor
        run: |
          pip install git+https://x-access-token:${{secrets.ORG_PAT}}@github.com/GraphVertexColoring/graph-feat.git
      
      - name: Extract Features
        run: python .github/scripts/run_extractor.py

      - name: Checkout coloring Repository
        uses: actions/checkout@v4
        with:
          repository: GraphVertexColoring/coloring
          token: ${{ secrets.ORG_PAT }}
          path: coloring
          
      - name: Push Feature file
        run: |
          cd coloring
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          cp ../InstanceFeatures.csv ./Resources/InstanceFeatures.csv 
          git add .
          git commit -m "Automated feature extraction results"
          git push origin master